name: DYNATECH Operations
favicon: null
layout_spectrum: 0.9503451937343925
typography_spectrum: 0.7002198845148087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2127464439254254
  lightness: 0.5573941261973232
  saturation: 0.21582490555010736
  rhythmicContrast: 0.8399850272107869
purpose: []
